package src.pojo;
// Generated Aug 8, 2016 11:10:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String description;
     private Set mappings = new HashSet(0);

    public Location() {
    }

    public Location(String code, String description, Set mappings) {
       this.code = code;
       this.description = description;
       this.mappings = mappings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMappings() {
        return this.mappings;
    }
    
    public void setMappings(Set mappings) {
        this.mappings = mappings;
    }




}


