package src.pojo;
// Generated Aug 8, 2016 11:10:30 AM by Hibernate Tools 4.3.1



/**
 * Mapping generated by hbm2java
 */
public class Mapping  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private Location location;

    public Mapping() {
    }

    public Mapping(Item item, Location location) {
       this.item = item;
       this.location = location;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }




}


